// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Jest   = require("bs-jest/lib/js/src/jest.js");
var Curry  = require("bs-platform/lib/js/curry.js");
var ReList = require("./reList.js");

describe("Append", (function () {
        return Jest.test("toBe", (function () {
                      return Curry._2(Jest.Expect[/* toBe */1], /* :: */[
                                  1,
                                  /* :: */[
                                    2,
                                    /* :: */[
                                      3,
                                      /* :: */[
                                        4,
                                        /* :: */[
                                          5,
                                          /* :: */[
                                            6,
                                            /* [] */0
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ], Curry._1(Jest.Expect[/* expect */0], ReList.append(/* :: */[
                                          1,
                                          /* :: */[
                                            2,
                                            /* :: */[
                                              3,
                                              /* [] */0
                                            ]
                                          ]
                                        ], /* :: */[
                                          4,
                                          /* :: */[
                                            5,
                                            /* :: */[
                                              6,
                                              /* [] */0
                                            ]
                                          ]
                                        ])));
                    }));
      }));

describe("Expect.Operators", (function () {
        return Jest.test("==", (function () {
                      return Curry._2(Jest.Expect[/* Operators */22][/* == */0], Curry._1(Jest.Expect[/* expect */0], 3), 3);
                    }));
      }));

/*  Not a pure module */
